### ISSUE TITLE
Better interaction with user in serial

### ISSUE THREAD

**Issue by Adman** [xlcteam/vic#29]
There are a couple of things I'm missing in serial console:
* `ls` command, which would show available commands that user has defined before.
* print "beign ~>"  on new line after the arduino has been restarted. So the user can be sure that something is causing arduino restart.
* print something like `~>` at the beggining of each line, so user is able to diferentiate between input and output string

I'd appreciate implementing these features. It would help us to detect problems a bit faster during testing, and also it would tidy up I/O stuff

**Comment by vargac** [comment]
@Adman @mrshu I think this issue has been solved and might be closed.

**Comment by mrshu** [comment]
@vargac roger that, thanks for dealing with it!
